### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by JeelPatel07** [ib-sundeep/rn-netflix-clone#2]
Hello,

Unable to resolve module ../secrets from /Users/{username}/Desktop/Project/rn-netflix-clone/api/tmdb.js.

Please update the `tmdb.js` file. Unable to run project.

Thank you

**Comment by ib-sundeep** [comment]
@JeelPatel07 Please create a file `secrets.json` on your local in the root of your project and add this content to it

```json
{
  "TMDB_API_KEY": "GET-YOUR-KEY-FROM-TMDB-AND-ADD-HERE"
}
```

**Comment by ib-sundeep** [comment]
@JeelPatel07 Updated the project with a README.md. Please refer to it for all steps
